'use client';
import { useCallback,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { API_URL,apiFetch,pedir,sesionActual } from '@/utils/api';
import { useSocket } from '@/context/SocketContext';
const fecha=(v:string|null)=>v?new Date(v).toLocaleString('es-MX'):'Pendiente';
const minutos=(v:number|null|undefined)=>v==null?'—':(v/60).toFixed(2);
export default function MuestrasID({area}:{area:'id'|'ventas'}){
 const router=useRouter(),socket=useSocket();
 const [sesion,setSesion]=useState<any>(null),[lista,setLista]=useState<any[]>([]),[pagina,setPagina]=useState(1),[total,setTotal]=useState(0);
 const [catalogos,setCatalogos]=useState<any>({viabilidades:[],procesos:[]}),[refs,setRefs]=useState<any>({productos:[],clientes:[]}),[busqueda,setBusqueda]=useState('');
 const [detalle,setDetalle]=useState<any>(null),[error,setError]=useState(''),[mensaje,setMensaje]=useState(''),[ocupado,setOcupado]=useState(false),[crear,setCrear]=useState(false),[etiqueta,setEtiqueta]=useState(false);
 const [plan,setPlan]=useState<number[]>([]),[nuevoCiclo,setNuevoCiclo]=useState(false),[proceso,setProceso]=useState(''),[resultado,setResultado]=useState(''),[terminando,setTerminando]=useState<number|null>(null);
 const [tipoCat,setTipoCat]=useState('proceso'),[catId,setCatId]=useState(''),[nombre,setNombre]=useState(''),[estandar,setEstandar]=useState(''),[activo,setActivo]=useState(true);
 const [verCatalogos,setVerCatalogos]=useState(false),[reporte,setReporte]=useState<any[]|null>(null),[desde,setDesde]=useState(''),[hasta,setHasta]=useState('');
 useEffect(()=>{const s=sesionActual();if(!s?.token||s.area!==area){router.replace('/');return;}setSesion(s);},[area,router]);
 const cargar=useCallback(async()=>{
  try{const [l,c]=await Promise.all([pedir(`/api/investigacion/muestras?pagina=${pagina}`,undefined,'GET'),pedir('/api/investigacion/catalogos',undefined,'GET')]);setLista(l.data);setTotal(l.total);setCatalogos(c);}catch(e){setError(e instanceof Error?e.message:'Error');}
 },[pagina]);
 const detalleId=detalle?.id_Muestra;
 useEffect(()=>{if(!sesion)return;void cargar();const refrescar=()=>{void cargar();if(detalleId)void pedir(`/api/investigacion/muestras/${detalleId}`,undefined,'GET').then(d=>setDetalle(d.data)).catch(e=>setError(e.message));};
  ['connect','ID_MUESTRA_ACTUALIZADA','ID_CATALOGO_ACTUALIZADO'].forEach(e=>socket?.on(e,refrescar));return()=>{['connect','ID_MUESTRA_ACTUALIZADA','ID_CATALOGO_ACTUALIZADO'].forEach(e=>socket?.off(e,refrescar));};
 },[sesion,socket,cargar,detalleId]);
 const ejecutar=async(fn:()=>Promise<any>,texto='Guardado correctamente')=>{
  if(ocupado)return;setOcupado(true);setError('');setMensaje('');try{await fn();await cargar();if(detalleId){const d=await pedir(`/api/investigacion/muestras/${detalleId}`,undefined,'GET');setDetalle(d.data);}setMensaje(texto);}catch(e){setError(e instanceof Error?e.message:'Error de conexión');}finally{setOcupado(false);}
 };
 const abrir=async(id:number)=>{try{const d=await pedir(`/api/investigacion/muestras/${id}`,undefined,'GET');setDetalle(d.data);setPlan([]);setNuevoCiclo(false);setTerminando(null);setEtiqueta(false);}catch(e){setError(e instanceof Error?e.message:'Error');}};
 const referencias=async()=>{try{const r=await pedir(`/api/investigacion/referencias?q=${encodeURIComponent(busqueda)}`,undefined,'GET');setRefs((prev:any)=>({productos:Array.from(new Map([...prev.productos,...r.productos].map((p:any)=>[p.id_Produc_Mater,p])).values()),clientes:Array.from(new Map([...prev.clientes,...r.clientes].map((p:any)=>[p.id_Persona,p])).values())}));}catch(e){setError(e instanceof Error?e.message:'Error');}};
 const registrar=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);data.set('fecha_recoleccion',new Date(String(data.get('fecha_recoleccion'))).toISOString());await ejecutar(async()=>{const r=await apiFetch(`${API_URL}/api/investigacion/muestras`,{method:'POST',body:data});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'No se pudo registrar');setCrear(false);await abrir(d.data.id_Muestra);},'Muestra registrada. Puedes imprimir su etiqueta.');};
 const descargarFicha=async()=>{try{const r=await apiFetch(`${API_URL}/api/investigacion/muestras/${detalleId}/ficha`);if(!r.ok)throw new Error('No se pudo descargar la ficha');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=detalle.ficha_nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Error');}};
 const cargarReporte=async()=>{await ejecutar(async()=>{const q=new URLSearchParams();if(desde)q.set('desde',new Date(desde).toISOString());if(hasta)q.set('hasta',new Date(hasta).toISOString());let pag=1,all:any[]=[];let n=0;do{q.set('pagina',String(pag++));const d=await pedir(`/api/investigacion/reporte?${q}`,undefined,'GET');all.push(...d.data);n=d.total;}while(all.length<n);setReporte(all);},'Reporte actualizado');};
 const csv=()=>{const campos=['id','muestra_id','ciclo','orden','nombre','estandar_version','estandar_segundos','disponible_desde','inicio','fin','duracionSegundos','esperaSegundos','desviacionSegundos','desviacionPorcentaje','inicio_por','fin_por'];const quote=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const texto=[campos.join(','),...(reporte||[]).map(p=>campos.map(k=>quote(p[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+texto],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='procesos_ID.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const guardarCatalogo=async(e:React.FormEvent)=>{e.preventDefault();await ejecutar(async()=>{await pedir(`/api/investigacion/catalogos/${tipoCat}`,{...(catId?{id:Number(catId)}:{}),nombre,activo,...(tipoCat==='proceso'?{estandar_segundos:estandar?Math.round(Number(estandar)*60):null}:{})},'PUT');setCatId('');setNombre('');setEstandar('');},'Catálogo actualizado. Los procesos ya planificados conservan su estándar.');};
 const ciclo=detalle?.procesos_id?.at(-1)?.ciclo??1,ejecuciones=(detalle?.procesos_id||[]).filter((p:any)=>p.ciclo===ciclo),finalizada=['APROBADO','RECHAZADO'].includes(detalle?.estado_Muestra);
 if(!sesion)return <p className="p-6">Verificando sesión…</p>;
 return <main className="id-app max-w-7xl mx-auto p-4 sm:p-6 space-y-5 bg-slate-50 min-h-screen text-slate-800">
 <style>{`@media print { body * { visibility:hidden !important; } .etiqueta-id,.etiqueta-id * { visibility:visible !important; } .etiqueta-id { position:absolute !important;left:0;top:0;width:100%;border:1px solid #000;padding:12mm; } .no-print { display:none !important; } }`}</style>
 <header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-bold">{area==='ventas'?'Ventas · Muestras para I+D':'Investigación y Desarrollo'}</h1><p className="text-sm text-slate-500">{sesion.usuario} · {area==='ventas'?'Tus muestras registradas':'Recepción, procesos y comparación con estándares'}</p></div><button onClick={async()=>{try{await pedir('/api/auth/salir');}finally{localStorage.removeItem('sesion');window.dispatchEvent(new Event('sesion-cambiada'));router.push('/');}}} className="border rounded px-4">Cerrar sesión</button></header>
 {error&&<p role="alert" className="rounded bg-red-100 text-red-800 p-3">{error}</p>}{mensaje&&<p role="status" className="rounded bg-emerald-100 p-3">{mensaje}</p>}
 <div className="flex flex-wrap gap-2"><button className="border p-2 rounded" onClick={()=>void cargar()}>Actualizar</button>{area==='ventas'?<button className="bg-blue-700 text-white p-2 rounded" onClick={()=>{setCrear(!crear);setDetalle(null);void referencias();}}>Registrar muestra</button>:<button className="border p-2 rounded" onClick={()=>setVerCatalogos(!verCatalogos)}>Viabilidades y estándares</button>}</div>
 {crear&&area==='ventas'&&<section className="bg-white border rounded-xl p-4 space-y-4"><h2 className="font-bold">Nueva muestra</h2><div className="flex flex-wrap gap-2"><input aria-label="Buscar producto o cliente" className="border p-2" value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Buscar producto o cliente"/><button type="button" className="border p-2" onClick={()=>void referencias()}>Buscar en catálogos</button></div>
 <form onSubmit={registrar} className="grid sm:grid-cols-2 gap-4">
 <label>Producto<select required name="producto_id" className="block border p-2 w-full"><option value="">Seleccionar</option>{refs.productos.map((p:any)=><option key={p.id_Produc_Mater} value={p.id_Produc_Mater}>{p.nombre_Producto}</option>)}</select></label>
 <label>Cliente<select required name="cliente_id" className="block border p-2 w-full"><option value="">Seleccionar</option>{refs.clientes.map((p:any)=><option key={p.id_Persona} value={p.id_Persona}>{p.nombre}</option>)}</select></label>
 <label>Caracterización<select name="caracterizacion" className="block border p-2 w-full"><option value="FILTRACION">Filtración</option><option value="REGENERACION">Regeneración</option></select></label>
 <label>Viabilidad<select required name="viabilidad_id" className="block border p-2 w-full"><option value="">Seleccionar</option>{catalogos.viabilidades.filter((v:any)=>v.activo).map((v:any)=><option key={v.id} value={v.id}>{v.nombre}</option>)}</select>{!catalogos.viabilidades.some((v:any)=>v.activo)&&<small>I+D debe configurar las opciones primero.</small>}</label>
 <label>Cantidad por proyecto<input name="cantidad_proyecto" required type="number" min="0.0001" step="0.0001" className="block border p-2 w-full"/></label><label>Unidad<input name="unidad_proyecto" required maxLength={30} placeholder="Ej. L, kg" className="block border p-2 w-full"/></label>
 <label>Fecha y hora de recolección<input required name="fecha_recoleccion" type="datetime-local" className="block border p-2 w-full"/><small>Hora local de este equipo.</small></label>
 <label>Ficha técnica · Word/PDF<input required name="ficha" type="file" accept=".pdf,.doc,.docx" className="block border p-2 w-full"/><small>Hasta 10 MB.</small></label>
 <label className="sm:col-span-2">Observaciones<textarea name="observaciones" maxLength={4000} className="block border p-2 w-full"/></label><p>La fecha de ingreso al laboratorio se registra al recibir la muestra.</p><button disabled={ocupado} className="bg-blue-700 text-white rounded p-2 disabled:opacity-50">Guardar muestra</button>
 </form></section>}
 {verCatalogos&&area==='id'&&<section className="border rounded-xl p-4 bg-white space-y-3"><h2 className="font-bold">Catálogos configurables</h2><form onSubmit={guardarCatalogo} className="flex flex-wrap gap-3 items-end"><label>Catálogo<select className="block border p-2" value={tipoCat} onChange={e=>{setTipoCat(e.target.value);setCatId('');setNombre('');setEstandar('');setActivo(true);}}><option value="proceso">Procesos / ensayos</option><option value="viabilidad">Viabilidades</option></select></label><label>Nombre<input required maxLength={100} value={nombre} onChange={e=>setNombre(e.target.value)} className="block border p-2"/></label>{tipoCat==='proceso'&&<label>Estándar (minutos)<input type="number" min="0.0167" step="any" value={estandar} onChange={e=>setEstandar(e.target.value)} className="block border p-2" placeholder="Vacío = sin estándar"/></label>}<label><input type="checkbox" checked={activo} onChange={e=>setActivo(e.target.checked)}/> Activo</label><button disabled={ocupado} className="border p-2 rounded">{catId?'Actualizar':'Agregar'}</button></form><div className="flex flex-wrap gap-2">{(tipoCat==='proceso'?catalogos.procesos:catalogos.viabilidades).map((p:any)=><button key={p.id} className="border rounded p-2 text-sm" onClick={()=>{setCatId(String(p.id));setNombre(p.nombre);setActivo(p.activo);setEstandar(p.estandar_segundos==null?'':String(p.estandar_segundos/60));}}>{p.nombre}{tipoCat==='proceso'?` · ${minutos(p.estandar_segundos)} min · v${p.version}`:''}{!p.activo?' · Inactivo':''}</button>)}</div></section>}
 <section className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{lista.map(m=><button key={m.id_Muestra} onClick={()=>void abrir(m.id_Muestra)} className="text-left bg-white border rounded-xl p-4 space-y-1"><span className="text-xs text-blue-700">{m.no_Muestra}</span><h2 className="font-bold">{m.productos_materiales.nombre_Producto}</h2><p>{m.personas_muestras_cliente_idTopersonas?.nombre}</p><p className="text-sm">{m.estado_Muestra} · {m.caracterizacion}</p><p className="text-xs">Ingreso: {fecha(m.fecha_ingreso_laboratorio)}</p></button>)}</section>
 <div className="flex items-center gap-3"><button disabled={pagina===1} onClick={()=>setPagina(p=>p-1)} className="border p-2">Anterior</button><span>Página {pagina} · {total} muestras</span><button disabled={pagina*50>=total} onClick={()=>setPagina(p=>p+1)} className="border p-2">Siguiente</button></div>
 {detalle&&<section className="bg-white border rounded-xl p-4 space-y-4"><header className="flex flex-wrap justify-between gap-3"><h2 className="font-bold text-lg">{detalle.no_Muestra}</h2><div className="flex flex-wrap gap-2"><button onClick={()=>setEtiqueta(!etiqueta)} className="border p-2">Etiqueta</button><button onClick={()=>void descargarFicha()} className="border p-2">Ficha técnica</button><button onClick={()=>{setDetalle(null);setEtiqueta(false);}} className="border p-2">Cerrar</button></div></header>
 <p>{detalle.productos_materiales.nombre_Producto} · {detalle.personas_muestras_cliente_idTopersonas?.nombre} · {detalle.cantidad_proyecto} {detalle.unidad_proyecto}</p><p>Recolección: {fecha(detalle.fecha_recoleccion)} · Ingreso: {fecha(detalle.fecha_ingreso_laboratorio)} · Viabilidad: {detalle.viabilidad_nombre}</p>
 {area==='id'&&<><div className="flex flex-wrap gap-2">{!detalle.fecha_ingreso_laboratorio&&<button disabled={ocupado} onClick={()=>void ejecutar(()=>pedir(`/api/investigacion/muestras/${detalleId}/recibir`))} className="bg-blue-700 text-white p-2 rounded">Recibir en laboratorio</button>}</div>
 {(!ejecuciones.some((p:any)=>p.inicio)||finalizada)&&<div className="border rounded p-3 space-y-2"><h3 className="font-bold">{finalizada?'Plan de nuevo ciclo':'Plan de procesos en orden de ejecución'}</h3><div className="flex flex-wrap gap-2"><select value={proceso} onChange={e=>setProceso(e.target.value)} className="border p-2"><option value="">Seleccionar proceso</option>{catalogos.procesos.filter((p:any)=>p.activo).map((p:any)=><option key={p.id} value={p.id}>{p.nombre} · {minutos(p.estandar_segundos)} min</option>)}</select><button onClick={()=>{if(proceso)setPlan(p=>[...p,Number(proceso)]);}} className="border p-2">Agregar al final</button><button onClick={()=>setPlan([])} className="border p-2">Limpiar selección</button></div><ol className="list-decimal pl-5">{plan.map((pid,i)=><li key={i}>{catalogos.procesos.find((p:any)=>p.id===pid)?.nombre} <button onClick={()=>setPlan(p=>p.filter((_,j)=>i!==j))} className="text-red-700">Quitar</button></li>)}</ol><button disabled={ocupado||!plan.length} onClick={()=>void ejecutar(()=>pedir(`/api/investigacion/muestras/${detalleId}/plan`,{procesos:plan,nuevoCiclo:finalizada}))} className="border p-2 rounded">{finalizada?'Abrir nuevo ciclo con este plan':'Guardar plan y estándares'}</button></div>}
 </>}
 <h3 className="font-bold">Procesos · ciclo actual {ciclo} (historial completo abajo)</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Ciclo / proceso','Disponible','Inicio','Fin','Real (min)','Espera (min)','Estándar (min)','Desviación','Acciones'].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{detalle.procesos_id.map((p:any)=><tr key={p.id} className="border-t"><td className="p-2">{p.ciclo}.{p.orden} {p.nombre}<p className="text-xs">{p.resultado}</p></td><td>{fecha(p.disponible_desde)}</td><td>{fecha(p.inicio)}</td><td>{fecha(p.fin)}</td><td>{minutos(p.duracionSegundos)}</td><td>{minutos(p.esperaSegundos)}</td><td>{minutos(p.estandar_segundos)} · v{p.estandar_version}</td><td className={p.desviacionSegundos>0?'text-red-700':''}>{p.desviacionPorcentaje==null?'Sin comparación':`${p.desviacionPorcentaje.toFixed(1)}%`}</td><td>{area==='id'&&p.ciclo===ciclo&&!finalizada&&(!p.inicio?<button disabled={ocupado||!detalle.fecha_ingreso_laboratorio||ejecuciones.some((x:any)=>x.orden<p.orden&&!x.fin)} onClick={()=>void ejecutar(()=>pedir(`/api/investigacion/muestras/${detalleId}/procesos/${p.id}/iniciar`))} className="border p-2 rounded disabled:opacity-40">Iniciar</button>:!p.fin?<button disabled={ocupado} onClick={()=>{setTerminando(p.id);setResultado('');}} className="border p-2 rounded">Terminar</button>:null)}</td></tr>)}</tbody></table></div>
 {terminando&&<form onSubmit={e=>{e.preventDefault();void ejecutar(async()=>{await pedir(`/api/investigacion/muestras/${detalleId}/procesos/${terminando}/terminar`,{resultado});setTerminando(null);});}} className="space-y-2"><label>Resultado / observaciones del proceso<textarea required maxLength={8000} value={resultado} onChange={e=>setResultado(e.target.value)} className="border p-2 block w-full"/></label><button disabled={ocupado} className="border rounded p-2">Guardar resultado y hora final</button></form>}
 {area==='id'&&!finalizada&&ejecuciones.length>0&&ejecuciones.every((p:any)=>p.fin)&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void ejecutar(()=>pedir(`/api/investigacion/muestras/${detalleId}/finalizar`,{dictamen:f.get('dictamen'),observaciones:f.get('observaciones')}));}} className="flex flex-wrap gap-2"><select name="dictamen" className="border p-2"><option>APROBADO</option><option>RECHAZADO</option></select><input name="observaciones" placeholder="Observaciones del dictamen" className="border p-2"/><button disabled={ocupado} className="bg-emerald-700 text-white rounded p-2">Finalizar ciclo</button></form>}
 <details><summary>Bitácora de eventos</summary>{detalle.eventos.map((e:any)=><p key={e.id} className="border-t py-2 text-xs break-words">{fecha(e.fecha)} · Ciclo {e.ciclo} · {e.accion} · {e.detalle}</p>)}</details>
 </section>}
 {etiqueta&&detalle&&<section className="etiqueta-id bg-white border-2 rounded p-5 space-y-2"><h2 className="font-bold text-xl">US Technologies · Muestra I+D</h2><p className="break-all">Folio: {detalle.no_Muestra}</p><p><b>Producto:</b> {detalle.productos_materiales.nombre_Producto}</p><p><b>Cliente:</b> {detalle.personas_muestras_cliente_idTopersonas?.nombre}</p><p><b>Caracterización:</b> {detalle.caracterizacion}</p><p><b>Cantidad por proyecto:</b> {detalle.cantidad_proyecto} {detalle.unidad_proyecto}</p><p><b>Viabilidad:</b> {detalle.viabilidad_nombre}</p><p><b>Recolección:</b> {fecha(detalle.fecha_recoleccion)}</p><p><b>Ingreso a laboratorio:</b> {fecha(detalle.fecha_ingreso_laboratorio)}</p><p><b>Ficha técnica:</b> {detalle.ficha_nombre}</p><p>Consulta y descarga con el folio en el módulo I+D.</p><button onClick={()=>window.print()} className="no-print border rounded p-2">Imprimir etiqueta</button></section>}
 {area==='id'&&<section className="bg-white border rounded-xl p-4 space-y-3"><h2 className="font-bold">Comparación de tiempos y esperas</h2><p className="text-sm">Etapas iniciadas en el rango. Las etapas abiertas y las que no tienen estándar no se usan como cero. Las esperas son tiempo calendario.</p><div className="flex flex-wrap gap-3"><label>Inicio desde<input type="datetime-local" value={desde} onChange={e=>setDesde(e.target.value)} className="border p-2 block"/></label><label>Inicio antes de<input type="datetime-local" value={hasta} onChange={e=>setHasta(e.target.value)} className="border p-2 block"/></label><button disabled={ocupado} onClick={()=>void cargarReporte()} className="border p-2">Consultar</button>{reporte&&<button onClick={csv} className="border p-2">Exportar CSV</button>}</div>{reporte&&<ResumenProcesos filas={reporte}/>}</section>}
 </main>;
}
function ResumenProcesos({filas}:{filas:any[]}){
 const grupos:Record<string,any[]>={};filas.forEach(p=>{(grupos[`${p.proceso_id} · ${p.nombre} · v${p.estandar_version}`]??=[]).push(p);});
 return <div className="overflow-auto"><p>{filas.length} ejecuciones · {filas.filter(p=>p.inicio&&!p.fin).length} en curso</p><table className="w-full text-sm"><thead><tr>{['Proceso / estándar','Terminados','Promedio real (min)','Espera media (min)','Sobre estándar'].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{Object.entries(grupos).map(([g,items])=>{const fin=items.filter(p=>p.duracionSegundos!=null),wait=items.filter(p=>p.esperaSegundos!=null),comp=fin.filter(p=>p.estandar_segundos!=null);return <tr key={g} className="border-t"><td>{g}</td><td>{fin.length}</td><td>{fin.length?minutos(fin.reduce((s,p)=>s+p.duracionSegundos,0)/fin.length):'—'}</td><td>{wait.length?minutos(wait.reduce((s,p)=>s+p.esperaSegundos,0)/wait.length):'—'}</td><td>{comp.length?`${comp.filter(p=>p.desviacionSegundos>0).length} / ${comp.length}`:'Sin estándar'}</td></tr>})}</tbody></table></div>;
}
